name: tvb-r306c-sim
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.11
  - ipykernel=6.29.5
  - notebook=7.3.2
  - numpy
  - matplotlib
  - h5py
  - scipy
  - pip
  - pip:
      - tvb-library==2.9.2
      - tvb-framework==2.9.1
      - allensdk==2.16.2
      - specparam
